# Generated by Django 2.1 on 2018-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='house',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
