# Generated by Django 2.1 on 2018-10-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='video',
            field=models.TextField(blank=True, default=''),
        ),
    ]
